# Generated by Django 4.1.2 on 2023-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_photo',
            name='image',
            field=models.ImageField(db_index=True, default='user_images/default_male.png', upload_to='user_images/%Y/%m/%d/'),
        ),
    ]
