# Generated by Django 4.1.2 on 2023-05-02 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersPortal', '0002_alter_user_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='location_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='usersPortal.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_contactnumber',
            name='contactNumber_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactNumber', to='usersPortal.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_photo',
            name='photo_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pic', to='usersPortal.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
