# Generated by Django 4.1.2 on 2023-04-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminportal', '0001_initial'),
        ('registrarportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsections',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_section', through='adminportal.class_student', to='registrarportal.student_enrollment_details'),
        ),
        migrations.AddField(
            model_name='schoolsections',
            name='sy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_section', to='registrarportal.schoolyear'),
        ),
    ]
