# Generated by Django 4.1.2 on 2023-04-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminportal', '0001_initial'),
        ('registrarportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsections',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_section', through='adminportal.class_student', to='registrarportal.student_enrollment_details'),
        ),
        migrations.AddField(
            model_name='schoolsections',
            name='sy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_section', to='registrarportal.schoolyear'),
        ),
        migrations.AddField(
            model_name='firstsemschedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='firstSemSched', to='adminportal.schoolsections'),
        ),
        migrations.AddField(
            model_name='firstsemschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='firstSemSubjectSchedule', to='adminportal.subjects'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='g11_firstSem_subjects',
            field=models.ManyToManyField(related_name='grade11_firstSem', to='adminportal.subjects'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='g11_secondSem_subjects',
            field=models.ManyToManyField(related_name='grade11_secondSem', to='adminportal.subjects'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='g12_firstSem_subjects',
            field=models.ManyToManyField(related_name='grade12_firstSem', to='adminportal.subjects'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='g12_secondSem_subjects',
            field=models.ManyToManyField(related_name='grade12_secondSem', to='adminportal.subjects'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='curriculum_strand', to='adminportal.shs_strand'),
        ),
        migrations.AddField(
            model_name='class_student',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='class_group', to='registrarportal.student_enrollment_details'),
        ),
        migrations.AddField(
            model_name='class_student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classmate', to='adminportal.schoolsections'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolsections',
            unique_together={('sy', 'name')},
        ),
    ]
