# Generated by Django 4.1.2 on 2023-03-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0019_note'),
        ('adminportal', '0004_auto_20230226_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstsemschedule',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='secondsemschedule',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='schoolsections',
            name='yearLevel',
            field=models.CharField(choices=[('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2),
        ),
        migrations.CreateModel(
            name='class_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='class_group', to='registrarportal.student_enrollment_details')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classmate', to='adminportal.schoolsections')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='schoolsections',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_section', through='adminportal.class_student', to='registrarportal.student_enrollment_details'),
        ),
    ]
