# Generated by Django 4.1.2 on 2023-04-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_auto_20230402_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondsemschedule',
            name='namo',
        ),
    ]
