# Generated by Django 4.1.2 on 2023-04-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_remove_secondsemschedule_namo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_email',
            name='email_from',
        ),
        migrations.DeleteModel(
            name='school_contact_number',
        ),
        migrations.DeleteModel(
            name='school_email',
        ),
    ]
