# Generated by Django 4.1.2 on 2023-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0003_auto_20230421_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dual_citizen_documents',
            name='dual_citizenship',
            field=models.ImageField(db_index=True, upload_to='admission/dualCitizenDocuments/dualCitizenshipCertificates/%Y'),
        ),
        migrations.AlterField(
            model_name='dual_citizen_documents',
            name='f137',
            field=models.ImageField(db_index=True, upload_to='admission/dualCitizenDocuments/f137s/%Y'),
        ),
        migrations.AlterField(
            model_name='dual_citizen_documents',
            name='good_moral',
            field=models.ImageField(db_index=True, upload_to='admission/goodMorals/%Y'),
        ),
        migrations.AlterField(
            model_name='dual_citizen_documents',
            name='philippine_passport',
            field=models.ImageField(db_index=True, upload_to='admission/dualCitizenDocuments/phPassports/%Y'),
        ),
        migrations.AlterField(
            model_name='dual_citizen_documents',
            name='psa',
            field=models.ImageField(db_index=True, upload_to='admission/studentPsa/%Y'),
        ),
        migrations.AlterField(
            model_name='dual_citizen_documents',
            name='report_card',
            field=models.ImageField(db_index=True, upload_to='admission/reportCards/%Y'),
        ),
        migrations.AlterField(
            model_name='foreign_citizen_documents',
            name='alien_certificate_of_registration',
            field=models.ImageField(db_index=True, upload_to='admission/foreignCitizenDocuments/alienRegistration/%Y'),
        ),
        migrations.AlterField(
            model_name='foreign_citizen_documents',
            name='f137',
            field=models.ImageField(db_index=True, upload_to='admission/foreignCitizenDocuments/f137s/%Y'),
        ),
        migrations.AlterField(
            model_name='foreign_citizen_documents',
            name='good_moral',
            field=models.ImageField(db_index=True, upload_to='admission/goodMorals/%Y'),
        ),
        migrations.AlterField(
            model_name='foreign_citizen_documents',
            name='psa',
            field=models.ImageField(db_index=True, upload_to='admission/studentPsa/%Y'),
        ),
        migrations.AlterField(
            model_name='foreign_citizen_documents',
            name='report_card',
            field=models.ImageField(db_index=True, upload_to='admission/reportCards/%Y'),
        ),
        migrations.AlterField(
            model_name='foreign_citizen_documents',
            name='study_permit',
            field=models.ImageField(db_index=True, upload_to='admission/foreignCitizenDocuments/studyPermit/%Y'),
        ),
        migrations.AlterField(
            model_name='ph_born',
            name='good_moral',
            field=models.ImageField(db_index=True, upload_to='admission/goodMorals/%Y'),
        ),
        migrations.AlterField(
            model_name='ph_born',
            name='psa',
            field=models.ImageField(db_index=True, upload_to='admission/studentPsa/%Y'),
        ),
        migrations.AlterField(
            model_name='ph_born',
            name='report_card',
            field=models.ImageField(db_index=True, upload_to='admission/reportCards/%Y'),
        ),
        migrations.AlterField(
            model_name='student_id_picture',
            name='user_image',
            field=models.ImageField(db_index=True, upload_to='enrollment/user_pic/%Y'),
        ),
        migrations.AlterField(
            model_name='student_report_card',
            name='report_card',
            field=models.ImageField(db_index=True, upload_to='enrollment/report_cards/%Y'),
        ),
    ]
