# Generated by Django 4.1.2 on 2023-04-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0003_student_grades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_grades',
        ),
    ]
