# Generated by Django 4.1.2 on 2023-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0005_student_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_grades',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
