# Generated by Django 4.1.2 on 2023-04-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0006_alter_student_grades_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_grades',
        ),
    ]
