# Generated by Django 4.1.2 on 2023-04-28 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrarportal', '0006_alter_student_admission_details_student_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission_details',
            name='audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audited_admission', to=settings.AUTH_USER_MODEL),
        ),
    ]
