# Generated by Django 4.1.2 on 2023-04-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0008_student_grades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='note',
        ),
    ]
