# Generated by Django 4.1.2 on 2023-04-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0008_student_enrollment_details_audited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission_details',
            name='student_lrn',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
