# Generated by Django 4.1.2 on 2023-05-02 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrarportal', '0009_alter_student_admission_details_student_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dual_citizen_documents',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softCopy_admissionRequirements_dualCitizen', to='registrarportal.student_admission_details'),
        ),
        migrations.AlterField(
            model_name='enrollment_invitations',
            name='invitation_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='registrarportal.student_admission_details'),
        ),
        migrations.AlterField(
            model_name='foreign_citizen_documents',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softCopy_admissionRequirements_foreigner', to='registrarportal.student_admission_details'),
        ),
        migrations.AlterField(
            model_name='ph_born',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softCopy_admissionRequirements_phBorn', to='registrarportal.student_admission_details'),
        ),
        migrations.AlterField(
            model_name='student_admission_details',
            name='admission_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_contact_number',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_contactnumber', to='registrarportal.student_enrollment_details'),
        ),
        migrations.AlterField(
            model_name='student_contact_number',
            name='own_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_enrollment_details',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='registrarportal.student_admission_details'),
        ),
        migrations.AlterField(
            model_name='student_enrollment_details',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_grades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_home_address',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_address', to='registrarportal.student_enrollment_details'),
        ),
        migrations.AlterField(
            model_name='student_home_address',
            name='home_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_id_picture',
            name='image_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_pict', to='registrarportal.student_enrollment_details'),
        ),
        migrations.AlterField(
            model_name='student_report_card',
            name='card_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card', to='registrarportal.student_enrollment_details'),
        ),
    ]
