# Generated by Django 4.1.2 on 2023-03-06 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0017_enrollment_invitations_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_contact_number',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='enrollment_contactnumber', to='registrarportal.student_enrollment_details'),
        ),
        migrations.AddField(
            model_name='student_home_address',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='enrollment_address', to='registrarportal.student_enrollment_details'),
        ),
    ]
