# Generated by Django 4.1.2 on 2023-03-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_alter_firstsemschedule_options_and_more'),
        ('registrarportal', '0019_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enrollment_batch_manager',
        ),
        migrations.AlterField(
            model_name='enrollment_batch',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='section_batch', to='adminportal.schoolsections'),
        ),
    ]
