# Generated by Django 4.1.2 on 2023-03-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0020_delete_enrollment_batch_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment_batch',
            options={'ordering': ['created_on', 'section']},
        ),
    ]
