# Generated by Django 4.1.2 on 2023-03-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0021_alter_enrollment_batch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment_batch',
            options={'ordering': ['created_on']},
        ),
    ]
