# Generated by Django 4.1.2 on 2023-03-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0022_alter_enrollment_batch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment_batch',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrollment_batch_member', to='registrarportal.student_enrollment_details'),
        ),
    ]
