# Generated by Django 4.1.2 on 2023-04-21 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentportal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentRequestedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
