# Generated by Django 4.1.2 on 2023-05-02 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentportal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentRequestedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
