# Generated by Django 4.1.2 on 2023-04-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentrequest',
            unique_together=set(),
        ),
    ]
